# This contains params to be used by the stages to train or predict

IMAGE_SIZE: [224, 224, 3] # IMAGE SIZE USED IN VGG16 MODEL 
BATCH_SIZE: 16 # default 32
EPOCHS: 2
LEARNING_RATE: 0.001
AUGMENTATION: True